repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-check
        files: ^Languages/Python/(main\.py|app/service/main\.py|app/service/api/app\.py|app/desktop/bootstrap/main\.py)$
        args: ["--config", "Languages/Python/pyproject.toml"]
